(define (encode message tree)
  (if (null? message)
    '()
    (append (encode-symbol (car message) tree)
            (encode (cdr message) tree))))

(define (encode-symbol symbol tree)
  (if (element-of-set? symbol (symbols tree))
    (cond ((leaf? tree) '())
          ((element-of-set? symbol (symbols (left-branch tree)))
           (cons '0 (encode-symbol symbol (left-branch tree))))
          ((element-of-set? symbol (symbols (right-branch tree)))
           (cons '1 (encode-symbol symbol (right-branch tree))))
          (error "Bad symbol -- ENCODE-SYMBOL" symbol))))

