(load "exercise.interval.arithmetic.scm")

(define r1 (make-center-percent 10 1))
(define r2 (make-center-percent 20 2))

(define p1 (par1 r1 r2))
(define p2 (par2 r1 r2))

(newline)
(newline)
(newline)
(display "r1 : ")
(display r1)
(newline)
(display "r2 : ")
(display r2)
(newline)
(display "par1 r1 r2 : ")
(display p1)
(newline)
(display "par2 r1 r2 : ")
(display p2)
(newline)

(display "tolerance par1 : ")
(display (percent p1))
(newline)

(display "tolerance par2 : ")
(display (percent p2))
(newline)
(newline)
(newline)
(display "Ava Lu Ator is right because in par1,")
(newline)
(display "mul-interval sums the tolerances, but in par2")
(newline)
(display "both of the div-intervals have one as an argument.")
(newline)
(display "Since the one has zero tolerance, the sum of the tolerances")
(newline)
(display "will be smaller than those in par1")
(newline)
(newline)
(newline)
