(load "exercise.interval.arithmetic.scm")

(define A (make-center-percent 20 1))
(define B (make-center-percent 30 1))

(define a-over-a (div-interval A A))
(define a-over-b (div-interval A B))

(newline)
(newline)
(newline)
(display "A/A : ")
(display a-over-a)
(newline)
(display "tolerance A : ")
(display (percent A))
(newline)
(display "tolerance A/A : ")
(display (percent a-over-a))
(newline)
(newline)
(display "A/B : ")
(newline)
(display a-over-b)
(display "tolerance A : ")
(display (percent A))
(newline)
(display "tolerance B : ")
(display (percent B))
(newline)
(display "tolerance A/B : ")
(display (percent a-over-b))
(newline)
(newline)
(display "It seems tolerance of a division of two intervals")
(newline)
(display "is cummulated. It is because the devision is applied by")
(newline)
(display "an inverse multiplication")
(newline)
(newline)
