(define (make-account initial credential)
  (lambda (password m)
    (if (eq? password credential)
      (cond ((eq? m 'withdraw)
             (lambda (amount)
               (if (< amount initial) 
                 (begin (set! initial (- initial amount)) initial)
                 "Insufficient funds")))
            ((eq? m 'deposit) 
             (lambda (amount) 
               (begin (set! initial (+ initial amount)) initial)))
            (else (error "Unknown request -- MAKE-ACCOUNT" m)))
      (lambda (any) "Incorrect password"))))

