(define (call-the-cops) "I am calling the cops")

(define (make-account initial credential)
  (define incorrect-count 0)
  (lambda (password m)
    (if (eq? password credential)
      (cond ((eq? m 'withdraw)
             (lambda (amount)
               (if (< amount initial) 
                 (begin (set! initial (- initial amount)) initial)
                 "Insufficient funds")))
            ((eq? m 'deposit) 
             (lambda (amount) 
               (begin (set! initial (+ initial amount)) initial)))
            (else (error "Unknown request -- MAKE-ACCOUNT" m)))
      (lambda (any)
        (if (> incorrect-count 7)
          (call-the-cops)
          (begin (set! incorrect-count (+ incorrect-count 1))
                 "Incorrect password"))))))

